services:
  - type: web
    name: ignite-tcm
    runtime: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails server -p $PORT -e production
    envVars:
      - key: RAILS_ENV
        value: production
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_PASSWORD
        sync: false